import { Order, Shipment, Business, Route, Branch, CurrentRoute, BusinessOrder, Invoice, Contract, Driver, AdminContext } from "./types";

export const mockShipments: Shipment[] = [
    {
        id: "ENV-001",
        orders: 12,
        currentBranch: "Sucursal Rosario",
        lastUpdate: "14:30",
        estimatedDuration: "4h 30m",
        totalDistance: "145 km",
        status: "En ruta",
        driver: "Carlos Mendez",
    },
    {
        id: "ENV-002",
        orders: 8,
        currentBranch: "Sucursal Buenos Aires",
        lastUpdate: "13:45",
        estimatedDuration: "2h 15m",
        totalDistance: "89 km",
        status: "En sucursal",
        driver: "Ana Rodriguez",
    },
    {
        id: "ENV-003",
        orders: 15,
        currentBranch: "Sucursal Córdoba",
        lastUpdate: "15:20",
        estimatedDuration: "6h 10m",
        totalDistance: "203 km",
        status: "Demorado",
        driver: "Luis Garcia",
    },
];

export const mockBusinesses: Business[] = [
    {
        id: "COM-001",
        name: "TechStore SA",
        fiscalAddress: "Av. Libertador 1234, CABA",
        email: "contacto@techstore.com",
        status: "Habilitado",
        contractDuration: "12 meses",
        services: ["Retiro a domicilio", "Embalaje", "Transporte"],
        pendingInvoices: 0,
        totalDebt: 0,
    },
    {
        id: "COM-002",
        name: "Fashion Boutique",
        fiscalAddress: "Calle Florida 567, CABA",
        email: "info@fashionboutique.com",
        status: "Deshabilitado",
        contractDuration: "6 meses",
        services: ["Transporte"],
        pendingInvoices: 2,
        totalDebt: 45000,
    },
    {
        id: "COM-003",
        name: "Librería El Saber",
        fiscalAddress: "Av. Corrientes 890, CABA",
        email: "ventas@elsaber.com",
        status: "Habilitado",
        contractDuration: "3 meses",
        services: ["Retiro a domicilio", "Transporte"],
        pendingInvoices: 1,
        totalDebt: 12500,
    },
];

export const mockRoutes: Route[] = [
    {
        id: "RUT-001",
        name: "Buenos Aires - Córdoba",
        branches: ["Buenos Aires", "Rosario", "Villa María", "Córdoba"],
        estimatedTime: "8h 30m",
        segments: 4,
    },
    {
        id: "RUT-002",
        name: "Ruta Patagónica Norte",
        branches: ["Buenos Aires", "Bahía Blanca", "Viedma", "Trelew"],
        estimatedTime: "12h 45m",
        segments: 4,
    },
    {
        id: "RUT-003",
        name: "Ruta Litoral",
        branches: ["Buenos Aires", "Rosario", "Santa Fe", "Paraná", "Corrientes"],
        estimatedTime: "11h 00m",
        segments: 5,
    },
    {
        id: "RUT-004",
        name: "Ruta Noroeste",
        branches: ["Córdoba", "Santiago del Estero", "Tucumán", "Salta", "Jujuy"],
        estimatedTime: "14h 20m",
        segments: 5,
    },
    {
        id: "RUT-005",
        name: "Ruta Patagónica Sur",
        branches: ["Trelew", "Comodoro Rivadavia", "Río Gallegos", "Ushuaia"],
        estimatedTime: "16h 30m",
        segments: 4,
    },
    // ➕ Nuevas rutas
    {
        id: "RUT-006",
        name: "Ruta Cuyo",
        branches: ["Buenos Aires", "San Luis", "Mendoza", "San Juan"],
        estimatedTime: "13h 20m",
        segments: 4,
    },
    {
        id: "RUT-007",
        name: "Ruta Atlántica",
        branches: ["Buenos Aires", "La Plata", "Dolores", "Mar del Plata"],
        estimatedTime: "6h 40m",
        segments: 4,
    },
    {
        id: "RUT-008",
        name: "Ruta NEA",
        branches: ["Santa Fe", "Reconquista", "Resistencia", "Formosa"],
        estimatedTime: "10h 50m",
        segments: 4,
    },
    {
        id: "RUT-009",
        name: "Ruta Andina Sur",
        branches: ["Neuquén", "General Roca", "San Carlos de Bariloche", "Esquel"],
        estimatedTime: "12h 10m",
        segments: 4,
    },
];

export const mockBranches: Branch[] = [
    { id: "SUC-BA", name: "Sucursal Buenos Aires", location: "Av. 9 de Julio 1500, CABA", phone: "+54 11 4567-8900", email: "buenosaires@logisticasjb.com" },
    { id: "SUC-ROS", name: "Sucursal Rosario", location: "Bv. Oroño 800, Rosario, Santa Fe", phone: "+54 341 456-7890", email: "rosario@logisticasjb.com" },
    { id: "SUC-VM", name: "Sucursal Villa María", location: "Av. Sabattini 1200, Villa María", phone: "+54 353 461-1111", email: "villamaria@logisticasjb.com" },
    { id: "SUC-CBA", name: "Sucursal Córdoba", location: "Av. Colón 1000, Córdoba", phone: "+54 351 468-0000", email: "cordoba@logisticasjb.com" },
    { id: "SUC-BB", name: "Sucursal Bahía Blanca", location: "Av. Alem 900, Bahía Blanca", phone: "+54 291 455-0000", email: "bahiablanca@logisticasjb.com" },
    { id: "SUC-VID", name: "Sucursal Viedma", location: "Av. 25 de Mayo 300, Viedma", phone: "+54 2920 423-000", email: "viedma@logisticasjb.com" },
    { id: "SUC-TR", name: "Sucursal Trelew", location: "Av. Fontana 400, Trelew", phone: "+54 280 443-0000", email: "trelew@logisticasjb.com" },
    { id: "SUC-CMD", name: "Sucursal Comodoro Rivadavia", location: "Rivadavia 1200, Comodoro", phone: "+54 297 447-0000", email: "comodoro@logisticasjb.com" },
    { id: "SUC-RG", name: "Sucursal Río Gallegos", location: "Av. Kirchner 700, Río Gallegos", phone: "+54 2966 442-000", email: "riogallegos@logisticasjb.com" },
    { id: "SUC-USH", name: "Sucursal Ushuaia", location: "San Martín 500, Ushuaia", phone: "+54 2901 422-000", email: "ushuaia@logisticasjb.com" },
    { id: "SUC-SF", name: "Sucursal Santa Fe", location: "Bv. Gálvez 1500, Santa Fe", phone: "+54 342 455-0000", email: "santafe@logisticasjb.com" },
    { id: "SUC-PNA", name: "Sucursal Paraná", location: "Av. Almafuerte 1200, Paraná", phone: "+54 343 420-0000", email: "parana@logisticasjb.com" },
    { id: "SUC-CRR", name: "Sucursal Corrientes", location: "Av. 3 de Abril 800, Corrientes", phone: "+54 379 443-0000", email: "corrientes@logisticasjb.com" },
    { id: "SUC-SDE", name: "Sucursal Santiago del Estero", location: "Av. Belgrano 900, Sgo. del Estero", phone: "+54 385 421-0000", email: "santiago@logisticasjb.com" },
    { id: "SUC-TUC", name: "Sucursal Tucumán", location: "Av. Sarmiento 700, S. M. de Tucumán", phone: "+54 381 430-0000", email: "tucuman@logisticasjb.com" },
    { id: "SUC-SAL", name: "Sucursal Salta", location: "Av. San Martín 900, Salta", phone: "+54 387 421-0000", email: "salta@logisticasjb.com" },
    { id: "SUC-JUY", name: "Sucursal Jujuy", location: "Av. Hipólito Yrigoyen 600, S. S. de Jujuy", phone: "+54 388 423-0000", email: "jujuy@logisticasjb.com" },
    { id: "SUC-SLU", name: "Sucursal San Luis", location: "Av. Illia 500, San Luis", phone: "+54 266 442-0000", email: "sanluis@logisticasjb.com" },
    { id: "SUC-MZA", name: "Sucursal Mendoza", location: "Av. San Martín 1200, Mendoza", phone: "+54 261 423-0000", email: "mendoza@logisticasjb.com" },
    { id: "SUC-SJ", name: "Sucursal San Juan", location: "Av. Libertador 900, San Juan", phone: "+54 264 422-0000", email: "sanjuan@logisticasjb.com" },
    { id: "SUC-LP", name: "Sucursal La Plata", location: "Av. 7 800, La Plata", phone: "+54 221 422-0000", email: "laplata@logisticasjb.com" },
    { id: "SUC-MDP", name: "Sucursal Mar del Plata", location: "Av. Luro 2300, Mar del Plata", phone: "+54 223 493-0000", email: "mdp@logisticasjb.com" },
    { id: "SUC-RES", name: "Sucursal Resistencia", location: "Av. 9 de Julio 500, Resistencia", phone: "+54 362 442-0000", email: "resistencia@logisticasjb.com" },
    { id: "SUC-FOR", name: "Sucursal Formosa", location: "Av. 25 de Mayo 600, Formosa", phone: "+54 370 442-0000", email: "formosa@logisticasjb.com" },
    { id: "SUC-NQN", name: "Sucursal Neuquén", location: "Av. Argentina 200, Neuquén", phone: "+54 299 442-0000", email: "neuquen@logisticasjb.com" },
    { id: "SUC-GRO", name: "Sucursal General Roca", location: "Av. Roca 400, General Roca", phone: "+54 298 443-0000", email: "gralroca@logisticasjb.com" },
    { id: "SUC-BRC", name: "Sucursal San Carlos de Bariloche", location: "Mitre 600, Bariloche", phone: "+54 294 442-0000", email: "bariloche@logisticasjb.com" },
    { id: "SUC-ESQ", name: "Sucursal Esquel", location: "Av. Ameghino 700, Esquel", phone: "+54 2945 452-000", email: "esquel@logisticasjb.com" },
    { id: "SUC-REC", name: "Sucursal Reconquista", location: "Bv. Hipólito Yrigoyen 600, Reconquista", phone: "+54 3482 422-000", email: "reconquista@logisticasjb.com" },
];

export const mockDriverOrders: Order[] = [
    {
        id: "PED-001",
        recipient: "Juan Pérez",
        address: "Av. Corrientes 1234",
        neighborhood: "Balvanera",
        locality: "Buenos Aires (CABA)",
        phone: "+54 11 1234-5678",
        estimatedTime: "30 min",
        status: "pendiente",
        business: "TechStore SA",
        description: "Notebook Lenovo ThinkPad E14",
        weight: "2.5 kg",
        specialInstructions: "Entregar en portería, timbre 4B",
    },
    {
        id: "PED-004",
        recipient: "Ana Martínez",
        address: "Av. Rivadavia 2345",
        neighborhood: "Balvanera",
        locality: "Buenos Aires (CABA)",
        phone: "+54 11 4567-8901",
        estimatedTime: "50 min",
        status: "pendiente",
        business: "TechStore SA",
        description: "Mouse inalámbrico y teclado",
        weight: "1.1 kg",
        specialInstructions: "Dejar con portero si no está",
    },
    {
        id: "PED-002",
        recipient: "María González",
        address: "Calle Florida 567",
        neighborhood: "Microcentro",
        locality: "Buenos Aires (CABA)",
        phone: "+54 11 2345-6789",
        estimatedTime: "45 min",
        status: "pendiente",
        business: "Fashion Boutique",
        description: "Vestido de fiesta talla M",
        weight: "0.8 kg",
        specialInstructions: "Llamar antes de llegar",
    },
    {
        id: "PED-005",
        recipient: "Luis Rodríguez",
        address: "Av. Callao 1678",
        neighborhood: "Recoleta",
        locality: "Buenos Aires (CABA)",
        phone: "+54 11 5678-9012",
        estimatedTime: "1h 5min",
        status: "pendiente",
        business: "Fashion Boutique",
        description: "Zapatos deportivos talla 42",
        weight: "1.5 kg",
        specialInstructions: "Probar antes de entregar",
    },
    {
        id: "PED-003",
        recipient: "Carlos López",
        address: "Av. Santa Fe 890",
        neighborhood: "Retiro",
        locality: "Buenos Aires (CABA)",
        phone: "+54 11 3456-7890",
        estimatedTime: "1h 15min",
        status: "pendiente",
        business: "Librería El Saber",
        description: "Pack de libros universitarios",
        weight: "3.2 kg",
        specialInstructions: "Entregar solo al destinatario",
    },
    {
        id: "PED-006",
        recipient: "Pedro Fernández",
        address: "Av. Cabildo 3456",
        neighborhood: "Belgrano",
        locality: "Buenos Aires (CABA)",
        phone: "+54 11 6789-0123",
        estimatedTime: "1h 30min",
        status: "entregado",
        business: "TechStore SA",
        description: "Tablet Samsung Galaxy",
        weight: "0.6 kg",
        specialInstructions: "Entregado a portería",
    },
    // Nuevos pedidos con diferentes destinos
    {
        id: "PED-007",
        recipient: "Sandra Martín",
        address: "Av. Pellegrini 1250",
        neighborhood: "Centro",
        locality: "Rosario (Santa Fe)",
        phone: "+54 341 456-1234",
        estimatedTime: "2h 15min",
        status: "pendiente",
        business: "TechStore SA",
        description: "Monitor LED 24 pulgadas",
        weight: "4.2 kg",
        specialInstructions: "Entregar en horario comercial",
    },
    {
        id: "PED-008",
        recipient: "Roberto Silva",
        address: "Bv. San Juan 890",
        neighborhood: "Nueva Córdoba",
        locality: "Córdoba (Córdoba)",
        phone: "+54 351 468-5678",
        estimatedTime: "3h 45min",
        status: "pendiente",
        business: "Fashion Boutique",
        description: "Conjunto deportivo talla L",
        weight: "1.2 kg",
        specialInstructions: "Verificar talla antes de entregar",
    },
    {
        id: "PED-009",
        recipient: "Patricia Gómez",
        address: "Av. Mitre 567",
        neighborhood: "Centro",
        locality: "Rosario (Santa Fe)",
        phone: "+54 341 456-9876",
        estimatedTime: "2h 30min",
        status: "pendiente",
        business: "Librería El Saber",
        description: "Diccionario Oxford Español-Inglés",
        weight: "2.8 kg",
        specialInstructions: "Llamar 30 min antes",
    },
    {
        id: "PED-010",
        recipient: "Diego Herrera",
        address: "Calle 27 de Abril 432",
        neighborhood: "Centro",
        locality: "Córdoba (Córdoba)",
        phone: "+54 351 468-2345",
        estimatedTime: "3h 20min",
        status: "pendiente",
        business: "TechStore SA",
        description: "Impresora multifunción HP",
        weight: "8.5 kg",
        specialInstructions: "Requiere ayuda para subir al 3er piso",
    },
    {
        id: "PED-011",
        recipient: "Mónica Ramos",
        address: "Av. Colón 1895",
        neighborhood: "Alberdi",
        locality: "Córdoba (Córdoba)",
        phone: "+54 351 468-7890",
        estimatedTime: "3h 10min",
        status: "pendiente",
        business: "Fashion Boutique",
        description: "Cartera de cuero marrón",
        weight: "0.9 kg",
        specialInstructions: "Entregar solo a la destinataria",
    },
    {
        id: "PED-012",
        recipient: "Fernando Torres",
        address: "Av. Francia 2100",
        neighborhood: "Fisherton",
        locality: "Rosario (Santa Fe)",
        phone: "+54 341 456-3456",
        estimatedTime: "2h 45min",
        status: "pendiente",
        business: "Librería El Saber",
        description: "Colección de novelas argentinas (5 tomos)",
        weight: "4.1 kg",
        specialInstructions: "Verificar que estén completos los 5 tomos",
    },
    {
        id: "PED-013",
        recipient: "Claudia Vega",
        address: "Calle Mendoza 789",
        neighborhood: "Centro",
        locality: "Mendoza (Mendoza)",
        phone: "+54 261 423-1111",
        estimatedTime: "5h 30min",
        status: "pendiente",
        business: "TechStore SA",
        description: "Smartphone iPhone 15",
        weight: "0.8 kg",
        specialInstructions: "Verificar IMEI antes de entregar",
    },
    {
        id: "PED-014",
        recipient: "Gustavo Morales",
        address: "Av. San Martín 1456",
        neighborhood: "Godoy Cruz",
        locality: "Mendoza (Mendoza)",
        phone: "+54 261 423-2222",
        estimatedTime: "5h 15min",
        status: "pendiente",
        business: "Fashion Boutique",
        description: "Traje formal azul marino talla 48",
        weight: "2.3 kg",
        specialInstructions: "Probar antes de entregar",
    },
    {
        id: "PED-015",
        recipient: "Elena Castillo",
        address: "Bv. Chacabuco 654",
        neighborhood: "Centro",
        locality: "Salta (Salta)",
        phone: "+54 387 421-3333",
        estimatedTime: "7h 45min",
        status: "pendiente",
        business: "Librería El Saber",
        description: "Atlas geográfico de Argentina",
        weight: "3.5 kg",
        specialInstructions: "Entregar en biblioteca personal",
    },
    {
        id: "PED-016",
        recipient: "Marco Antonelli",
        address: "Av. Libertad 2890",
        neighborhood: "Centro",
        locality: "Tucumán (Tucumán)",
        phone: "+54 381 424-4444",
        estimatedTime: "6h 20min",
        status: "pendiente",
        business: "TechStore SA",
        description: "Laptop HP Pavilion 15",
        weight: "2.8 kg",
        specialInstructions: "Verificar funcionamiento antes de entregar",
    },
    {
        id: "PED-017",
        recipient: "Carmen Delgado",
        address: "Calle 25 de Mayo 567",
        neighborhood: "Centro",
        locality: "Santa Fe (Santa Fe)",
        phone: "+54 342 455-5555",
        estimatedTime: "4h 10min",
        status: "pendiente",
        business: "Fashion Boutique",
        description: "Abrigo de lana gris talla M",
        weight: "1.6 kg",
        specialInstructions: "Revisar que no tenga defectos",
    },
    {
        id: "PED-018",
        recipient: "Alejandro Ruiz",
        address: "Av. 7 N° 1234",
        neighborhood: "Centro",
        locality: "La Plata (Buenos Aires)",
        phone: "+54 221 456-6666",
        estimatedTime: "1h 45min",
        status: "pendiente",
        business: "Librería El Saber",
        description: "Manual de Derecho Civil (3 tomos)",
        weight: "5.2 kg",
        specialInstructions: "Entregar solo al destinatario con DNI",
    },
    {
        id: "PED-019",
        recipient: "Natalia Moreno",
        address: "Bv. Oroño 3456",
        neighborhood: "Centro",
        locality: "Rosario (Santa Fe)",
        phone: "+54 341 456-7777",
        estimatedTime: "2h 20min",
        status: "pendiente",
        business: "TechStore SA",
        description: "Auriculares Bluetooth Sony",
        weight: "0.5 kg",
        specialInstructions: "Probar conexión antes de entregar",
    },
    {
        id: "PED-020",
        recipient: "Jorge Villalba",
        address: "Calle Independencia 890",
        neighborhood: "Alberdi",
        locality: "Córdoba (Córdoba)",
        phone: "+54 351 468-8888",
        estimatedTime: "3h 35min",
        status: "pendiente",
        business: "Fashion Boutique",
        description: "Zapatillas running Adidas talla 44",
        weight: "1.8 kg",
        specialInstructions: "Verificar talla y modelo",
    },
    {
        id: "PED-021",
        recipient: "Isabel Navarro",
        address: "Av. Las Heras 2100",
        neighborhood: "Las Heras",
        locality: "Mendoza (Mendoza)",
        phone: "+54 261 423-9999",
        estimatedTime: "5h 50min",
        status: "pendiente",
        business: "Librería El Saber",
        description: "Enciclopedia Británica (12 tomos)",
        weight: "15.8 kg",
        specialInstructions: "Requiere dos personas para transportar",
    },
    {
        id: "PED-022",
        recipient: "Rodrigo Paz",
        address: "Calle Tucumán 432",
        neighborhood: "Centro",
        locality: "Tucumán (Tucumán)",
        phone: "+54 381 424-0000",
        estimatedTime: "6h 05min",
        status: "pendiente",
        business: "TechStore SA",
        description: "Smart TV Samsung 55 pulgadas",
        weight: "18.5 kg",
        specialInstructions: "Instalar y configurar en el lugar",
    },
    {
        id: "PED-023",
        recipient: "Valeria Castro",
        address: "Av. Belgrano 1678",
        neighborhood: "Centro",
        locality: "Santa Fe (Santa Fe)",
        phone: "+54 342 455-1111",
        estimatedTime: "4h 25min",
        status: "pendiente",
        business: "Fashion Boutique",
        description: "Vestido de noche negro talla S",
        weight: "0.7 kg",
        specialInstructions: "Entregar en funda protectora",
    },
    {
        id: "PED-024",
        recipient: "Esteban Romero",
        address: "Diagonal 74 N° 890",
        neighborhood: "Tolosa",
        locality: "La Plata (Buenos Aires)",
        phone: "+54 221 456-2222",
        estimatedTime: "1h 55min",
        status: "pendiente",
        business: "TechStore SA",
        description: "Teclado mecánico gaming RGB",
        weight: "1.2 kg",
        specialInstructions: "Verificar que funcionen todas las teclas",
    },
];

// Destinos adicionales para el selector
export const mockDestinations = [
    { id: "buenos-aires", name: "Buenos Aires", province: "CABA", orderCount: 5 },
    { id: "rosario", name: "Rosario", province: "Santa Fe", orderCount: 4 },
    { id: "cordoba", name: "Córdoba", province: "Córdoba", orderCount: 4 },
    { id: "mendoza", name: "Mendoza", province: "Mendoza", orderCount: 3 },
    { id: "salta", name: "Salta", province: "Salta", orderCount: 1 },
    { id: "tucuman", name: "Tucumán", province: "Tucumán", orderCount: 2 },
    { id: "santa-fe", name: "Santa Fe", province: "Santa Fe", orderCount: 2 },
    { id: "la-plata", name: "La Plata", province: "Buenos Aires", orderCount: 2 },
];


export const mockCurrentRoute: CurrentRoute = {
    name: "Ruta Buenos Aires - Córdoba",
    currentBranch: "Rosario",
    nextBranch: "Villa María",
    totalBranches: 4,
    branches: [
        { name: "Buenos Aires", status: "completed", time: "08:00" },
        { name: "Rosario", status: "current", time: "12:30" },
        { name: "Villa María", status: "pending", time: "15:00" },
        { name: "Córdoba", status: "pending", time: "17:30" },
    ],
    estimatedCompletion: "18:00",
};

// Datos mock para Comercio
export const mockBusinessOrders: BusinessOrder[] = [
    {
        id: "PED-COM-001",
        recipient: "Ana García",
        address: "Av. Libertador 1234",
        neighborhood: "Palermo",
        phone: "+54 11 1111-2222",
        status: "en_transito",
        description: "Smartphone Samsung Galaxy S24",
        weight: "0.5 kg",
        specialInstructions: "Llamar antes de llegar",
        createdAt: "2025-08-25",
        estimatedDelivery: "2025-08-28",
        totalAmount: 15000,
    },
    {
        id: "PED-COM-002",
        recipient: "Carlos Mendez",
        address: "Calle Corrientes 567",
        neighborhood: "Microcentro",
        phone: "+54 11 3333-4444",
        status: "entregado",
        description: "Auriculares Bluetooth",
        weight: "0.3 kg",
        specialInstructions: "Entregar en recepción",
        createdAt: "2025-08-20",
        estimatedDelivery: "2025-08-23",
        totalAmount: 8500,
    },
    {
        id: "PED-COM-003",
        recipient: "María Rodriguez",
        address: "Av. Santa Fe 890",
        neighborhood: "Recoleta",
        phone: "+54 11 5555-6666",
        status: "pendiente",
        description: "Laptop Lenovo ThinkPad",
        weight: "2.5 kg",
        specialInstructions: "Entregar solo al destinatario",
        createdAt: "2025-08-27",
        estimatedDelivery: "2025-08-30",
        totalAmount: 25000,
    },
    {
        id: "PED-COM-004",
        recipient: "Luis Fernández",
        address: "Av. Cabildo 1122",
        neighborhood: "Belgrano",
        phone: "+54 11 7777-8888",
        status: "cancelado",
        description: "Tablet iPad Air",
        weight: "0.7 kg",
        specialInstructions: "Cancelado por el cliente",
        createdAt: "2025-08-15",
        estimatedDelivery: "2025-08-18",
        totalAmount: 18000,
    },
];

export const mockInvoices: Invoice[] = [
    {
        id: "FAC-001",
        businessId: "COM-001",
        amount: 48500,
        status: "pagada",
        issuedDate: "2025-08-01",
        dueDate: "2025-08-15",
        description: "Servicios de entrega - Agosto 2025",
        orders: ["PED-COM-001", "PED-COM-002"],
        services: ["Retiro a domicilio", "Transporte", "Embalaje"],
    },
    {
        id: "FAC-002",
        businessId: "COM-001",
        amount: 25000,
        status: "pendiente",
        issuedDate: "2025-08-15",
        dueDate: "2025-08-30",
        description: "Servicios de entrega - Segunda quincena Agosto",
        orders: ["PED-COM-003"],
        services: ["Retiro a domicilio", "Transporte"],
    },
    {
        id: "FAC-003",
        businessId: "COM-001",
        amount: 32000,
        status: "vencida",
        issuedDate: "2025-07-15",
        dueDate: "2025-07-30",
        description: "Servicios de entrega - Julio 2025",
        orders: ["PED-COM-004"],
        services: ["Transporte", "Embalaje"],
    },
];

export const mockContract: Contract = {
    id: "CONT-001",
    businessId: "COM-001",
    status: "activo",
    startDate: "2025-06-01",
    endDate: "2026-06-01",
    services: ["Retiro a domicilio", "Transporte", "Embalaje"],
    monthlyFee: 15000,
    pickupLimit: 50,
    deliveryLimit: 100,
};

export const mockAvailableServices = [
    {
        id: "SRV-001",
        name: "Retiro a domicilio",
        description: "Retiro de productos en tu comercio",
        monthlyFee: 5000,
    },
    {
        id: "SRV-002",
        name: "Transporte",
        description: "Servicio de transporte a destino",
        monthlyFee: 8000,
    },
    {
        id: "SRV-003",
        name: "Embalaje",
        description: "Embalaje profesional de productos",
        monthlyFee: 3000,
    },
    {
        id: "SRV-004",
        name: "Seguro",
        description: "Seguro contra daños y pérdidas",
        monthlyFee: 2000,
    },
    {
        id: "SRV-005",
        name: "Tracking SMS",
        description: "Notificaciones SMS de seguimiento",
        monthlyFee: 1500,
    },
];

// Mock data for drivers
export const mockDrivers: Driver[] = [
    {
        id: "DRV-001",
        name: "Carlos Mendez",
        branch: "Buenos Aires",
        branchId: "SUC-BA",
        status: "available",
        phone: "+54 11 1234-5678",
        vehicleCapacity: "20 pedidos",
        currentRoute: null,
    },
    {
        id: "DRV-002",
        name: "Ana Rodriguez",
        branch: "Buenos Aires",
        branchId: "SUC-BA",
        status: "available",
        phone: "+54 11 2345-6789",
        vehicleCapacity: "15 pedidos",
        currentRoute: null,
    },
    {
        id: "DRV-003",
        name: "Luis Garcia",
        branch: "Buenos Aires",
        branchId: "SUC-BA",
        status: "busy",
        phone: "+54 11 3456-7890",
        vehicleCapacity: "25 pedidos",
        currentRoute: "ENV-003",
    },
    {
        id: "DRV-004",
        name: "Maria Fernandez",
        branch: "Córdoba",
        branchId: "SUC-CBA",
        status: "available",
        phone: "+54 351 468-1111",
        vehicleCapacity: "18 pedidos",
        currentRoute: null,
    },
    {
        id: "DRV-005",
        name: "Roberto Silva",
        branch: "Rosario",
        branchId: "SUC-ROS",
        status: "available",
        phone: "+54 341 456-1111",
        vehicleCapacity: "22 pedidos",
        currentRoute: null,
    },
    {
        id: "DRV-006",
        name: "Patricia López",
        branch: "Buenos Aires",
        branchId: "SUC-BA",
        status: "available",
        phone: "+54 11 4567-8901",
        vehicleCapacity: "18 pedidos",
        currentRoute: null,
    },
    {
        id: "DRV-007",
        name: "Diego Martínez",
        branch: "Buenos Aires",
        branchId: "SUC-BA",
        status: "available",
        phone: "+54 11 5678-9012",
        vehicleCapacity: "30 pedidos",
        currentRoute: null,
    },
    {
        id: "DRV-008",
        name: "Sandra Flores",
        branch: "Buenos Aires",
        branchId: "SUC-BA",
        status: "available",
        phone: "+54 11 6789-0123",
        vehicleCapacity: "16 pedidos",
        currentRoute: null,
    },
    {
        id: "DRV-009",
        name: "Miguel Torres",
        branch: "Córdoba",
        branchId: "SUC-CBA",
        status: "available",
        phone: "+54 351 468-2222",
        vehicleCapacity: "24 pedidos",
        currentRoute: null,
    },
    {
        id: "DRV-010",
        name: "Elena Vega",
        branch: "Rosario",
        branchId: "SUC-ROS",
        status: "available",
        phone: "+54 341 456-3333",
        vehicleCapacity: "20 pedidos",
        currentRoute: null,
    },
    {
        id: "DRV-011",
        name: "Fernando Gutiérrez",
        branch: "Buenos Aires",
        branchId: "SUC-BA",
        status: "busy",
        phone: "+54 11 7890-1234",
        vehicleCapacity: "28 pedidos",
        currentRoute: "ENV-004",
    },
    {
        id: "DRV-012",
        name: "Carla Mendoza",
        branch: "Buenos Aires",
        branchId: "SUC-BA",
        status: "available",
        phone: "+54 11 8901-2345",
        vehicleCapacity: "19 pedidos",
        currentRoute: null,
    },
];

// Mock administrator context (logged-in admin)
export const mockAdminContext: AdminContext = {
    id: "ADM-001",
    name: "Juan Pérez",
    branch: "Buenos Aires",
    branchId: "SUC-BA",
    role: "Administrator",
};
