import { Order, Shipment, Business, Route, Branch, CurrentRoute, BusinessOrder, Invoice, Contract } from "./types";

export const mockShipments: Shipment[] = [
    {
        id: "ENV-001",
        orders: 12,
        currentBranch: "Sucursal Centro",
        lastUpdate: "14:30",
        estimatedDuration: "4h 30m",
        totalDistance: "145 km",
        status: "En ruta",
        driver: "Carlos Mendez",
    },
    {
        id: "ENV-002",
        orders: 8,
        currentBranch: "Sucursal Norte",
        lastUpdate: "13:45",
        estimatedDuration: "2h 15m",
        totalDistance: "89 km",
        status: "En sucursal",
        driver: "Ana Rodriguez",
    },
    {
        id: "ENV-003",
        orders: 15,
        currentBranch: "Sucursal Sur",
        lastUpdate: "15:20",
        estimatedDuration: "6h 10m",
        totalDistance: "203 km",
        status: "Demorado",
        driver: "Luis Garcia",
    },
];

export const mockBusinesses: Business[] = [
    {
        id: "COM-001",
        name: "TechStore SA",
        fiscalAddress: "Av. Libertador 1234, CABA",
        email: "contacto@techstore.com",
        status: "Habilitado",
        contractDuration: "12 meses",
        services: ["Retiro a domicilio", "Embalaje", "Transporte"],
        pendingInvoices: 0,
        totalDebt: 0,
    },
    {
        id: "COM-002",
        name: "Fashion Boutique",
        fiscalAddress: "Calle Florida 567, CABA",
        email: "info@fashionboutique.com",
        status: "Deshabilitado",
        contractDuration: "6 meses",
        services: ["Transporte"],
        pendingInvoices: 2,
        totalDebt: 45000,
    },
    {
        id: "COM-003",
        name: "Librería El Saber",
        fiscalAddress: "Av. Corrientes 890, CABA",
        email: "ventas@elsaber.com",
        status: "Habilitado",
        contractDuration: "3 meses",
        services: ["Retiro a domicilio", "Transporte"],
        pendingInvoices: 1,
        totalDebt: 12500,
    },
];

export const mockRoutes: Route[] = [
    {
        id: "RUT-001",
        name: "Ruta Buenos Aires - Córdoba",
        branches: ["Buenos Aires", "Rosario", "Villa María", "Córdoba"],
        estimatedTime: "8h 30m",
        segments: 4,
    },
    {
        id: "RUT-002",
        name: "Ruta Patagónica Norte",
        branches: ["Buenos Aires", "Bahía Blanca", "Viedma", "Trelew"],
        estimatedTime: "12h 45m",
        segments: 4,
    },
    {
        id: "RUT-003",
        name: "Ruta Litoral",
        branches: ["Buenos Aires", "Santa Fe", "Paraná", "Corrientes"],
        estimatedTime: "10h 15m",
        segments: 4,
    },
    {
        id: "RUT-004",
        name: "Ruta Noroeste",
        branches: ["Córdoba", "Santiago del Estero", "Tucumán", "Salta", "Jujuy"],
        estimatedTime: "14h 20m",
        segments: 5,
    },
    {
        id: "RUT-005",
        name: "Ruta Patagónica Sur",
        branches: ["Trelew", "Comodoro Rivadavia", "Río Gallegos", "Ushuaia"],
        estimatedTime: "16h 30m",
        segments: 4,
    },
];

export const mockBranches: Branch[] = [
    {
        id: "SUC-001",
        name: "Sucursal Centro",
        location: "Av. 9 de Julio 1500, CABA",
        phone: "+54 11 4567-8901",
        email: "centro@logisticasjb.com",
    },
    {
        id: "SUC-002",
        name: "Sucursal Norte",
        location: "Av. Cabildo 2300, CABA",
        phone: "+54 11 4567-8902",
        email: "norte@logisticasjb.com",
    },
    {
        id: "SUC-003",
        name: "Sucursal Sur",
        location: "Av. Rivadavia 8900, CABA",
        phone: "+54 11 4567-8903",
        email: "sur@logisticasjb.com",
    },
];

export const mockDriverOrders: Order[] = [
    {
        id: "PED-001",
        recipient: "Juan Pérez",
        address: "Av. Corrientes 1234",
        neighborhood: "Balvanera",
        phone: "+54 11 1234-5678",
        estimatedTime: "30 min",
        status: "pendiente",
        business: "TechStore SA",
        description: "Notebook Lenovo ThinkPad E14",
        weight: "2.5 kg",
        specialInstructions: "Entregar en portería, timbre 4B",
    },
    {
        id: "PED-004",
        recipient: "Ana Martínez",
        address: "Av. Rivadavia 2345",
        neighborhood: "Balvanera",
        phone: "+54 11 4567-8901",
        estimatedTime: "50 min",
        status: "pendiente",
        business: "TechStore SA",
        description: "Mouse inalámbrico y teclado",
        weight: "1.1 kg",
        specialInstructions: "Dejar con portero si no está",
    },
    {
        id: "PED-002",
        recipient: "María González",
        address: "Calle Florida 567",
        neighborhood: "Microcentro",
        phone: "+54 11 2345-6789",
        estimatedTime: "45 min",
        status: "pendiente",
        business: "Fashion Boutique",
        description: "Vestido de fiesta talla M",
        weight: "0.8 kg",
        specialInstructions: "Llamar antes de llegar",
    },
    {
        id: "PED-005",
        recipient: "Luis Rodríguez",
        address: "Av. Callao 1678",
        neighborhood: "Recoleta",
        phone: "+54 11 5678-9012",
        estimatedTime: "1h 5min",
        status: "pendiente",
        business: "Fashion Boutique",
        description: "Zapatos deportivos talla 42",
        weight: "1.5 kg",
        specialInstructions: "Probar antes de entregar",
    },
    {
        id: "PED-003",
        recipient: "Carlos López",
        address: "Av. Santa Fe 890",
        neighborhood: "Retiro",
        phone: "+54 11 3456-7890",
        estimatedTime: "1h 15min",
        status: "pendiente",
        business: "Librería El Saber",
        description: "Pack de libros universitarios",
        weight: "3.2 kg",
        specialInstructions: "Entregar solo al destinatario",
    },
    {
        id: "PED-006",
        recipient: "Pedro Fernández",
        address: "Av. Cabildo 3456",
        neighborhood: "Belgrano",
        phone: "+54 11 6789-0123",
        estimatedTime: "1h 30min",
        status: "entregado",
        business: "TechStore SA",
        description: "Tablet Samsung Galaxy",
        weight: "0.6 kg",
        specialInstructions: "Entregado a portería",
    },
];

export const mockCurrentRoute: CurrentRoute = {
    name: "Ruta Buenos Aires - Córdoba",
    currentBranch: "Rosario",
    nextBranch: "Villa María",
    totalBranches: 4,
    branches: [
        { name: "Buenos Aires", status: "completed", time: "08:00" },
        { name: "Rosario", status: "current", time: "12:30" },
        { name: "Villa María", status: "pending", time: "15:00" },
        { name: "Córdoba", status: "pending", time: "17:30" },
    ],
    estimatedCompletion: "18:00",
};

// Datos mock para Comercio
export const mockBusinessOrders: BusinessOrder[] = [
    {
        id: "PED-COM-001",
        recipient: "Ana García",
        address: "Av. Libertador 1234",
        neighborhood: "Palermo",
        phone: "+54 11 1111-2222",
        status: "en_transito",
        description: "Smartphone Samsung Galaxy S24",
        weight: "0.5 kg",
        specialInstructions: "Llamar antes de llegar",
        createdAt: "2025-08-25",
        estimatedDelivery: "2025-08-28",
        totalAmount: 15000,
    },
    {
        id: "PED-COM-002",
        recipient: "Carlos Mendez",
        address: "Calle Corrientes 567",
        neighborhood: "Microcentro",
        phone: "+54 11 3333-4444",
        status: "entregado",
        description: "Auriculares Bluetooth",
        weight: "0.3 kg",
        specialInstructions: "Entregar en recepción",
        createdAt: "2025-08-20",
        estimatedDelivery: "2025-08-23",
        totalAmount: 8500,
    },
    {
        id: "PED-COM-003",
        recipient: "María Rodriguez",
        address: "Av. Santa Fe 890",
        neighborhood: "Recoleta",
        phone: "+54 11 5555-6666",
        status: "pendiente",
        description: "Laptop Lenovo ThinkPad",
        weight: "2.5 kg",
        specialInstructions: "Entregar solo al destinatario",
        createdAt: "2025-08-27",
        estimatedDelivery: "2025-08-30",
        totalAmount: 25000,
    },
    {
        id: "PED-COM-004",
        recipient: "Luis Fernández",
        address: "Av. Cabildo 1122",
        neighborhood: "Belgrano",
        phone: "+54 11 7777-8888",
        status: "cancelado",
        description: "Tablet iPad Air",
        weight: "0.7 kg",
        specialInstructions: "Cancelado por el cliente",
        createdAt: "2025-08-15",
        estimatedDelivery: "2025-08-18",
        totalAmount: 18000,
    },
];

export const mockInvoices: Invoice[] = [
    {
        id: "FAC-001",
        businessId: "COM-001",
        amount: 48500,
        status: "pagada",
        issuedDate: "2025-08-01",
        dueDate: "2025-08-15",
        description: "Servicios de entrega - Agosto 2025",
        orders: ["PED-COM-001", "PED-COM-002"],
        services: ["Retiro a domicilio", "Transporte", "Embalaje"],
    },
    {
        id: "FAC-002",
        businessId: "COM-001",
        amount: 25000,
        status: "pendiente",
        issuedDate: "2025-08-15",
        dueDate: "2025-08-30",
        description: "Servicios de entrega - Segunda quincena Agosto",
        orders: ["PED-COM-003"],
        services: ["Retiro a domicilio", "Transporte"],
    },
    {
        id: "FAC-003",
        businessId: "COM-001",
        amount: 32000,
        status: "vencida",
        issuedDate: "2025-07-15",
        dueDate: "2025-07-30",
        description: "Servicios de entrega - Julio 2025",
        orders: ["PED-COM-004"],
        services: ["Transporte", "Embalaje"],
    },
];

export const mockContract: Contract = {
    id: "CONT-001",
    businessId: "COM-001",
    status: "activo",
    startDate: "2025-06-01",
    endDate: "2026-06-01",
    services: ["Retiro a domicilio", "Transporte", "Embalaje"],
    monthlyFee: 15000,
    pickupLimit: 50,
    deliveryLimit: 100,
};

export const mockAvailableServices = [
    {
        id: "SRV-001",
        name: "Retiro a domicilio",
        description: "Retiro de productos en tu comercio",
        monthlyFee: 5000,
    },
    {
        id: "SRV-002",
        name: "Transporte",
        description: "Servicio de transporte a destino",
        monthlyFee: 8000,
    },
    {
        id: "SRV-003",
        name: "Embalaje",
        description: "Embalaje profesional de productos",
        monthlyFee: 3000,
    },
    {
        id: "SRV-004",
        name: "Seguro",
        description: "Seguro contra daños y pérdidas",
        monthlyFee: 2000,
    },
    {
        id: "SRV-005",
        name: "Tracking SMS",
        description: "Notificaciones SMS de seguimiento",
        monthlyFee: 1500,
    },
];
